version: "3"

services:

  orders:
    image: hefnawi/microservice-api:v0.1
    environment:
      - DEBUG=True
      - SECRET_KEY=orders-zulu-demo003
      - JWT_ACCESS_LIFESPAN=24
      - JWT_REFRESH_LIFESPAN=30
      - SESSION_SECRET
    networks:
      - flask
    deploy:
      restart_policy:
        condition: any
    networks:
      - proxy
      - default


  products:
    image: hefnawi/microservice-api:v0.1
    environment:
      - DEBUG=True
      - SECRET_KEY=products-zulu-demo003
      - JWT_ACCESS_LIFESPAN=24
      - JWT_REFRESH_LIFESPAN=30
      - SESSION_SECRET
    networks:
      - flask
    deploy:
      restart_policy:
        condition: any
    networks:
      - proxy
      - default


networks:
  default:
    external: false
  proxy:
    external: true
