version: "3"

services:

  #TODO: create a common docker image for auth, products and orders
  auth:
    image: hefnawi/auth-microservice-api:v0.1
    container_name: auth
    environment:
      - DEBUG=True
      - SECRET_KEY=products-zulu-demo003
      - ACCESS_EXPIRES=15
      - REFRESH_EXPIRES=30
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis-net
      - default

  orders:
    image: hefnawi/orders-microservice-api:v0.1
    container_name: orders
    environment:
      - DEBUG=True
      - SECRET_KEY=products-zulu-demo003
      - ACCESS_EXPIRES=15
      - REFRESH_EXPIRES=30
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis-net
      - default
    volumes:
      - orders-json-data:/data


  products:
    image: hefnawi/products-microservice-api:v0.1
    container_name: products
    environment:
      - DEBUG=True
      - SECRET_KEY=products-zulu-demo003
      - ACCESS_EXPIRES=15
      - REFRESH_EXPIRES=30
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis-net
      - default
    volumes:
      - products-json-data:/data


  redis:
    image: redis:5.0-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
      - default
    volumes:
      - redis-data:/data


  nginx:
    image: hefnawi/nginx-api:v0.1
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    networks:
      - web
      - default


networks:
  default:
    external: false
  web:
    external: false
  redis-net:
    external: false


volumes:
  redis-data:
  products-json-data:
  orders-json-data:
